name: Build Mi Pad 6 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/upload-artifact@f2132016cfcafc6106be4dbf2bde0396b4c0c4f2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex git libncurses-dev libssl-dev \
        python-is-python3 unzip zip zstd

    - name: Download Clang
      run: |
        mkdir clang
        wget https://github.com/ClangBuiltLinux/llvm-project/releases/download/clang-r450784d/clang-r450784d.tar.gz
        tar -xf clang-r450784d.tar.gz -C clang
        echo "CLANG_PATH=$PWD/clang/clang-r450784d" >> $GITHUB_ENV
        echo "PATH=$PWD/clang/clang-r450784d/bin:$PATH" >> $GITHUB_ENV

    - name: Set environment variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV

    - name: Configure Kernel
      run: |
        make O=out pipa_user_defconfig

    - name: Build Kernel
      run: |
        make -j$(nproc) O=out \
          ARCH=arm64 \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi-

    - name: Upload kernel artifact
      uses: ./.github/actions/upload-artifact
      with:
        name: kernel
        path: out/arch/arm64/boot/
